# Generated by Django 3.0.5 on 2020-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counselor', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
