# Generated by Django 3.0.3 on 2020-03-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checklist', '0002_auto_20200331_0500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
