# Generated by Django 3.0.3 on 2020-04-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Counselor', '0001_initial'),
        ('student', '0002_auto_20200408_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='counselor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Counselor.CounselorProfile'),
        ),
    ]
