# Generated by Django 3.0.3 on 2020-03-31 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Counselor', '0001_initial'),
        ('student', '0002_auto_20200331_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='counselor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Counselor.CounselorProfile'),
            preserve_default=False,
        ),
    ]
