# Generated by Django 3.0.3 on 2020-04-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200408_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
