# Generated by Django 3.0.3 on 2020-03-31 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Counselor', '0001_initial'),
        ('student', '0005_auto_20200331_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='counselor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Counselor.CounselorProfile'),
        ),
    ]
