# Generated by Django 3.0.3 on 2020-04-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_lor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lor',
            name='post',
            field=models.CharField(default='HOD', max_length=200),
        ),
    ]
