# Generated by Django 3.0.3 on 2020-04-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200408_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='subject',
        ),
    ]
