# Generated by Django 3.0.3 on 2020-04-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_testing_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
    ]
