# Generated by Django 2.2.11 on 2020-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_act_activity_lor_sat_subjecttest_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
