# Generated by Django 3.0.3 on 2020-04-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.CharField(default='email', max_length=200),
        ),
    ]
