# Generated by Django 3.0.3 on 2020-04-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='token',
            field=models.CharField(default='wsdfghjk', max_length=11),
            preserve_default=False,
        ),
    ]
