# Generated by Django 3.0.3 on 2020-04-02 17:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0011_requests_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Invite',
        ),
        migrations.RenameField(
            model_name='invite',
            old_name='counselor',
            new_name='counselor_name',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='transcript',
            new_name='transcripts',
        ),
    ]
