# Generated by Django 3.0.5 on 2020-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
