# Generated by Django 3.0.5 on 2020-05-11 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20200503_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 17, 54, 7, 186289, tzinfo=utc), null=True),
        ),
    ]
