# Generated by Django 3.0.5 on 2020-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200511_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='newmessage',
            field=models.BooleanField(default=False),
        ),
    ]
