# Generated by Django 3.0.7 on 2020-06-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20200620_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='order',
        ),
        migrations.AddField(
            model_name='college',
            name='status',
            field=models.CharField(default='None', max_length=12),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
